# Generated by Django 4.1.2 on 2022-11-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_curso_creado'),
    ]

    operations = [
        migrations.CreateModel(
            name='haga_su_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('e_mail', models.EmailField(max_length=254)),
                ('cantidad_de_personas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipo_de_relleno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relleno', models.CharField(max_length=40)),
                ('crocante', models.CharField(max_length=40)),
                ('numero_de_pisos', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='curso_creado',
            new_name='tipo_de_postre',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.RenameField(
            model_name='tipo_de_postre',
            old_name='age',
            new_name='cantidad_de_personas',
        ),
        migrations.RenameField(
            model_name='tipo_de_postre',
            old_name='lastName',
            new_name='nombre_torta',
        ),
        migrations.RenameField(
            model_name='tipo_de_postre',
            old_name='name',
            new_name='relleno',
        ),
    ]
